server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AccidentalyAcross/microservicecloud-config.git #GitHub上面的git仓库名字
      label: master
      username: 1412613748@qq.com
      password: xf7644...

